---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: udi-cuda-base
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/devfile/developer-images.git'
    contextDir: /base/ubi8
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
      from:
        kind: ImageStreamTag
        name: 'cuda:11.8.0-devel-ubi8'
  output:
    to:
      kind: ImageStreamTag
      name: udi-cuda:base
  triggers:
    - type: ImageChange
    - type: ConfigChange
