apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: udi-cuda-kludge
  annotations:
    app.openshift.io/vcs-ref: main
    app.openshift.io/vcs-uri: https://github.com/redhat-na-ssa/demo-ocp-gpt2-keras-nlp.git
  labels:
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.11-ubi8
spec:
  output:
    to:
      kind: ImageStreamTag
      name: udi-cuda:kludge
  runPolicy: SerialLatestOnly
  source:
    type: dockerfile
    dockerfile: |
      FROM scratch

      WORKDIR /projects

      ENTRYPOINT ['/entrypoint.sh']
      CMD ['tail', '-f', '/dev/null']
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: quay.io/opendatahub/workbench-images:cuda-jupyter-tensorflow-ubi9-python-3.9-pr-222
    type: Docker
  triggers:
  - imageChange: {}
    type: ImageChange
  - type: ConfigChange
